---
conditions: v1
dist: xenial
language: python

git:
  depth: 200

cache:
  pip: true

python:
- "3.7"

before_install:
- deactivate
- pyenv global 3.7
- python3.7 -m pip install -U tox --user
install:
- python3.7 -m tox --notest

script:
- python3.7 -m tox

jobs:
  fast_finish: true
  include:
  - python: "3.7"
    name: Checking pre-commit linter compliance
    env:
      TOXENV: pre-commit-ci
  - python: "3.7"
    name: Checking docs build
    env:
      TOXENV: build-docs
  - python: "3.7"
    name: Running pytest test suite
    env:
      TOXENV: python
  - &deploy-job
    stage: Upload a new version of python package to PYPI
    name: Publishing current Git tagged version of dist to PyPI
    if: repo == "sanitizers/octomachinery" AND tag IS present
    python: "3.7"
    env:
      TOXENV: build-dists
    before_deploy:
    - echo > setup.py
    deploy: &deploy-step
      provider: pypi
      on:
        all_branches: true
        tags: true
      user: __token__
      password:
        secure: >-
          NihDbboQ/8fwKgk9Uv3+xH2Vww3cndtKDRAGrCRsKr8AfaCjqA/fwg8jcta3FEgpCAHRvATIc63bexSv5fn4iyDpiQYUFbHVTUiou/TwH+/o14LE5bSriB/fwWtfg6KKA+PO7IBPyzKP5Kn6U0YFPy0sTboYjGnHnqKSci/pbra8QTrVuOnbuFOC8oeg9eckl2k3TYPFm/sBU9YO4nPfXxkAQnNvvisVEEkljJ+RzP6h0uroTUXH6DTTyGb9IvK85no71M9LW3DlXdSss1gga7LpPCabEQlJmYr1SjlWT1wSFJihtiP+0aTo/UCNoUyFbWVyWd+f7mJpbMtAY57AmMF9BSqcvSOke6TOj5k3uIbqJ6ePvj7WUA8qE1AebOm4OcFK2tGBpp4rue97qHvAyYbDIg0Yo73OQx2WuWdB3GAlvuXw+7yRPtRuaEbUpYLV0rn34tbQlTEoK572VcPas18qcw8+EPLfJt/dbUsQUtDdu7gw6nXIuOOa8FOMPwt9fSls8ajpiHR+llGQ78aOIJDWGuhfBmlCUnzfZU2KtK/e8+ETQmdMVf9eqvSEAsyccNt+jTA8tSm11BvzV5HRruJlSao4dpo6U+EwZlf+CIzGUZVvbUhY5SNNhMGrufW5vBwY3NoCUQS2Srt20kELCiCeu1G1Pw1K4737ceTz1qw=
      distributions:
      skip-cleanup: true
  - <<: *deploy-job
    name: >-
      Publishing current (unstable) Git revision of dist to Test PyPI
      on every commit
    if: >-  # Always run, except if PR or cron
      repo == "sanitizers/octomachinery" AND
      branch == "master" AND
      type == "push"
    deploy:
      <<: *deploy-step
      password:  # Test PyPI has a separate account hence separately generated token
        secure: >-
          KORvGOUrSOrz90HmRdhu2FF0oszydzh0JW1DjkBKCmLlx/7dGN0YYsI+vaai6EBtoMMF7pRR/Hwc1Kc5OqjDnsVfIiPtVLld8whplYR3AflRN+X/rjiVoUiumBFUzJSzjhzk9lIUg3dSuiTrs/J+UPx1PriqfRi6eFdujQzqFg6LVnvHhC2C5BvcG15Y+PI+J0Z2o9snTJJvFM30Z3M+Xtr8df0XuWw7SM4NSaAtn+GvwBjXbQD9ehwJ5mpdQLVdln0dcKVOJkCMI8418XvT4AcyRQSKpc6z2+VRu+6TKqmtsfLfUpapiRjROltN+tMiHKVSLbu6zrYkelsAW8JIfAJO8oRqFThgV+gKq/3qsRVF7QTeDqkNJBosrdsxsCj5J5YJP0VQikgzkKPwUNG2lcKM1q7ErOKs7wz6GOB8meTs+sYVbYXOtiIXZhfSb+gUaNzFHcm+r5rt3zVIU7+lJHBsjTavGQXN88odSqpnuWKXIf5GirkBYyg4gcjoR9ID9WilBUHxd92cG9eiBAsXybimE9rnjSsVmX+TkvC/S9hXxGm+ew+5LARRAhVzhvCSwOpfHTo7HatBWr+/WFHrva1nNPt9ljTNy7OIOM4q43TDbMe9DqjqgtomUoMPIUgmUFNTt22Ib44ah9n5+Z3NEM0KKPPn1LVvNweo7KX5cwg=
      server: https://test.pypi.org/legacy/
      on:
        all_branches: true
